# Generated by Django 5.1.2 on 2026-01-14 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('party', 'Party'), ('formal', 'Formal'), ('traditional', 'Traditional')], max_length=50)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('rainy', 'Rainy'), ('all', 'All Season')], default='all', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wardrobe/')),
                ('last_worn', models.DateField(blank=True, null=True)),
                ('wear_count', models.IntegerField(default=0)),
                ('clean_status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
