# Generated by Django 5.1.2 on 2026-01-14 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_category_occasion_season_alter_wardrobeitem_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='last_worn',
        ),
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='wear_count',
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
