# Generated by Django 5.1.2 on 2026-04-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_outfitplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitplan',
            name='worn',
            field=models.BooleanField(default=False),
        ),
    ]
