# Generated by Django 4.2.27 on 2026-01-21 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0006_category_max_wears'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outfitrecommendation',
            unique_together={('user', 'top_item', 'bottom_item')},
        ),
        migrations.AddIndex(
            model_name='outfitrecommendation',
            index=models.Index(fields=['user', 'match_score'], name='recommendat_user_id_799020_idx'),
        ),
    ]
