# Generated by Django 4.2.27 on 2026-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_outfitrecommendation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorMatchingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_1', models.CharField(help_text="First color (e.g., 'red')", max_length=50)),
                ('color_2', models.CharField(help_text="Second color (e.g., 'green')", max_length=50)),
                ('score', models.FloatField(help_text='Match score from 0.0 (Bad) to 1.0 (Excellent)')),
            ],
            options={
                'verbose_name': 'Color Matching Rule',
                'verbose_name_plural': 'Color Matching Rules',
                'unique_together': {('color_1', 'color_2')},
            },
        ),
    ]
