# Generated by Django 4.2.27 on 2026-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_colormatchingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitrecommendation',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
