# Generated by Django 4.2.27 on 2026-01-21 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_outfitrecommendation_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colormatchingrule',
            name='score',
            field=models.FloatField(help_text='Match score from 0.0 (Bad) to 1.0 (Excellent)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
