# Generated by Django 5.1.2 on 2026-02-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_outfitfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitfeedback',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Checked by admin'),
        ),
    ]
