# Generated by Django 5.1.2 on 2026-04-10 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_outfitfeedback_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitfeedback',
            name='ai_review',
            field=models.TextField(blank=True, help_text="AI's reasoning for score adjustment", null=True),
        ),
        migrations.AlterField(
            model_name='outfitfeedback',
            name='rating',
            field=models.FloatField(help_text='User rating from 1.0 to 5.0', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
