# Generated by Django 5.1.2 on 2026-01-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.category'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.occasion'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.season'),
        ),
    ]
