# Generated by Django 5.1.2 on 2026-01-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_remove_wardrobeitem_last_worn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='wear_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
