# Generated by Django 5.1.2 on 2026-01-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_wardrobeitem_wear_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
