# Generated by Django 4.2.27 on 2026-01-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_alter_wardrobeitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_wears',
            field=models.PositiveIntegerField(default=1, help_text='Number of wears before cleaning is needed'),
        ),
    ]
