# Generated by Django 4.2.27 on 2026-01-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0006_category_max_wears'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wardrobeitem',
            index=models.Index(fields=['user', 'clean_status'], name='wardrobe_wa_user_id_58f386_idx'),
        ),
        migrations.AddIndex(
            model_name='wardrobeitem',
            index=models.Index(fields=['user', 'category'], name='wardrobe_wa_user_id_4c82dc_idx'),
        ),
    ]
