# Generated by Django 4.2.27 on 2026-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0007_wardrobeitem_wardrobe_wa_user_id_58f386_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
