# Generated by Django 4.2.27 on 2026-01-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0008_wardrobeitem_price_wardrobeitem_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='total_wears',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime wear count'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='wear_count',
            field=models.PositiveIntegerField(default=0, help_text='Current wears since last wash'),
        ),
    ]
