# Generated by Django 5.1.2 on 2026-01-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_type', models.CharField(choices=[('watch', 'Watch'), ('shoes', 'Shoes'), ('sandals', 'Sandals'), ('belt', 'Belt'), ('bag', 'Bag')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('party', 'Party'), ('formal', 'Formal'), ('traditional', 'Traditional')], max_length=50)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('rainy', 'Rainy'), ('all', 'All Season')], default='all', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
