# Generated by Django 5.1.2 on 2026-01-14 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_initial'),
        ('wardrobe', '0003_remove_wardrobeitem_last_worn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='color',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='accessory_type',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='image',
        ),
        migrations.AddField(
            model_name='accessory',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.occasion'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.season'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
