# Generated by Django 5.1.2 on 2026-01-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0004_accessory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
