# Generated by Django 4.2.27 on 2026-01-21 19:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0005_accessory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
