# Generated by Django 5.1.2 on 2026-04-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0006_alter_accessory_price_alter_accessory_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
