# Generated by Django 5.1.2 on 2026-01-14 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessories', '0002_initial'),
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottom_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_recommendations', to='wardrobe.wardrobeitem')),
                ('top_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_recommendations', to='wardrobe.wardrobeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.accessory')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_recommendations', to='recommendations.outfitrecommendation')),
            ],
        ),
    ]
